name: CI/CD PHP Login

on:
  workflow_dispatch:  # permite rodar manualmente
  workflow_call:      # permite ser chamado por outros workflows

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Instalar dependências
        run: |
          sudo apt-get install -y php-cli php-mbstring
          echo "Dependências instaladas."

      - name: Rodar testes
        run: |
          echo "Simulando testes..."
          if [ -f index.php ]; then
            php -l index.php
          else
            echo "index.php não encontrado. Pulando testes de sintaxe."
          fi

      - name: Build do projeto
        run: |
          echo "Build realizado com sucesso!"

      - name: Deploy (simulado)
        run: |
          echo "Realizando deploy..."
